"""The intake desk: messy chat messages in, clean order rows out.

YOU BUILD THIS. It is Lab 3.

Every function below raises until you implement it, so `pytest` runs and shows
you exactly which checks in tests/test_intake.py still fail. That failing list
is your specification - the feature is finished when it is empty.

The division of labour is the lesson. The model reads the language. The menu,
the arithmetic, the scoring and the decision about which orders a human has to
look at all stay in plain Python.

Do not edit this file by hand at the start. Ask your agent, following
labs/PROMPTS.md, and read what it writes.
"""

TODO = "You build this in Lab 3. See labs/LAB3.md."

# The shape every extracted order comes back in. `name` must be one of the
# menu items, spelled exactly as menu.md spells it - that is what lets
# order_total() price the order without any guessing.
# What to do with something that is not on the menu is a policy decision, and
# this is ours: drop the line we cannot fulfil, keep the rest of the order, and
# flag it. We do NOT substitute a different product - twenty hot lattes turning
# into twenty iced ones is the kind of "helpful" a business cannot afford - and
# we do NOT reject the whole order, because "one flat white and one croissant"
# should still sell a croissant.
#
# It has a cost, and Lab 3 asks you to find it: the customer's own words are
# kept only in `note`, as prose. Nothing structured survives, so nobody can
# ring them back to offer a Latte, and nobody can count how often people ask
# for mocha - which is exactly the number that tells you what to put on the
# menu. The fix is a field, not a better prompt.
ORDER_SCHEMA = {
    "type": "object",
    "properties": {
        "customer": {"type": "string"},
        "items": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "qty": {"type": "integer"},
                },
                "required": ["name", "qty"],
            },
        },
        "pickup": {"type": "string"},
        "needs_review": {"type": "boolean"},
        "note": {"type": "string"},
    },
    "required": ["customer", "items", "pickup", "needs_review", "note"],
}


def load_menu(path):
    """Read menu.md and return {item name: price in baht}.

    No language model involved. The menu is a table, tables are easy, and
    every call you do not make is a call that cannot go wrong.
    """
    raise NotImplementedError(TODO)


def order_total(order, menu):
    """What the order costs, in baht.

    The model extracted the items; your code does the arithmetic.
    Should raise ValueError naming any item that is not on the menu.
    """
    raise NotImplementedError(TODO)


def extract_one(message, menu_names, client=None):
    """One message in, one order out.

    Should return {"customer", "items", "pickup", "needs_review", "note"},
    with every item name taken from menu_names.
    """
    raise NotImplementedError(TODO)


def extract_batch(messages, menu_names, client=None):
    """Every message in ONE request, in the order you gave them.

    Ten messages in one request instead of ten requests: one round trip
    instead of ten, one set of instructions paid for once instead of ten
    times. It is cheaper and it is faster, and the answers are no worse.
    """
    raise NotImplementedError(TODO)


def score(extracted, answer_key):
    """Mark the extraction against the answer key. Plain Python, no model.

    Should return {"total", "exact", "by_field", "wrong_ids"}, comparing
    customer ignoring case, items in any order, and pickup exactly.
    """
    raise NotImplementedError(TODO)


def needs_review(extracted):
    """The ids a human has to look at before the café makes anything.

    Three reasons to escalate: the model said so itself, a field the kitchen
    needs came back empty, or a quantity that makes no sense.
    """
    raise NotImplementedError(TODO)
